app:
  message: heart rate data succesfully sent
spring:
  kafka:
    bootstrap-servers: 172.31.252.78:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8081

