app:
  message: heart rate data successfully sent
spring:
  kafka:
    bootstrap-servers: 192.168.1.13:9092
    consumer:
      group-id: ncc
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8081

