app:
  message: heart rate data succesfully sent
spring:
  rabbitmq:
    host: 192.168.1.2
    password: test
    port: 15672
    username: test
    exchange: epi.sport.exchange
    routingkey_hr: userheartrate.routingkey
server:
  port: 8081