spring:
  rabbitmq:
    host: 172.31.253.235
    password: test
    port: 15672
    username: test
    exchange: epi.sport.exchange
    queue_emergency: emergency.queue
    routingkey_emergency: emergency.routingkey
    routingkey_notif: notif.routingkey
  redis:
    hostname: 172.31.253.235
    port: 6379