spring:
  rabbitmq:
    host: 192.168.1.2
    password: test
    port: 15672
    username: test
    exchange: epi.sport.exchange
    queue_emergency: emergency.queue
    routingkey_emergency: emergency.routingkey
    routingkey_notif: notif.routingkey
  redis:
    hostname: 192.168.1.6
    port: 6379