spring:
  redis:
    hostname: 192.168.1.6
    port: 6379
  kafka:
    bootstrap-servers: 192.168.1.13:9092
    consumer:
      group-id: ncc
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"