spring:
  rabbitmq:
    host: 172.31.250.240
    password: test
    port: 15672
    username: test
    exchange: epi.sport.exchange
    queue_emergency: emergency.queue
    routingkey_emergency: emergency.routingkey
  redis:
    hostname: 172.31.250.241
    port: 6379