spring:
  rabbitmq:
    host: 172.31.252.111
    password: test
    port: 15672
    username: test
    exchange: epi.sport.exchange
    queue_emergency: emergency.queue
    routingkey_emergency: emergency.routingkey