
- name: "pull last version"
  hosts: localhost
  tasks :
    - name: "get last version"
      command: 
        cmd: git pull
        chdir: "{{ playbook_dir }}/../paas-epi-sport/"

- name: BUILD EVERYTHING
  hosts: all
  become: true
  roles:
    - role: ansible-springboot
