# Mandatory variable : path to springboot jar to deploy.
# Either specify a file or a url depending on if you want to copy you app or download it.

# Mandatory variable : spring boot application name
springboot_application_name: emergency-notification-agent 
